apiVersion: v1

name: ray-cluster

description: A Helm chart for deploying the RayCluster with the kuberay operator.

version: 1.1.0

home: https://github.com/ray-project/kuberay

icon: https://github.com/ray-project/ray/raw/master/doc/source/images/ray_header_logo.png
