{{- if .Values.webhooks.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kuberay-operator.webhook.certName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberay-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "kuberay-operator.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kuberay-operator.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "kuberay-operator.fullname" . }}-selfsigned-issuer
  secretName: {{ include "kuberay-operator.webhook.certSecretName" . }}
{{- end }}
