{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuberay-operator.webhook.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberay-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook-server
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "kuberay-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
