// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
	rayv1 "github.com/ray-project/kuberay/ray-operator/pkg/client/applyconfiguration/ray/v1"
	scheme "github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RayJobsGetter has a method to return a RayJobInterface.
// A group's client should implement this interface.
type RayJobsGetter interface {
	RayJobs(namespace string) RayJobInterface
}

// RayJobInterface has methods to work with RayJob resources.
type RayJobInterface interface {
	Create(ctx context.Context, rayJob *v1.RayJob, opts metav1.CreateOptions) (*v1.RayJob, error)
	Update(ctx context.Context, rayJob *v1.RayJob, opts metav1.UpdateOptions) (*v1.RayJob, error)
	UpdateStatus(ctx context.Context, rayJob *v1.RayJob, opts metav1.UpdateOptions) (*v1.RayJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.RayJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RayJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RayJob, err error)
	Apply(ctx context.Context, rayJob *rayv1.RayJobApplyConfiguration, opts metav1.ApplyOptions) (result *v1.RayJob, err error)
	ApplyStatus(ctx context.Context, rayJob *rayv1.RayJobApplyConfiguration, opts metav1.ApplyOptions) (result *v1.RayJob, err error)
	RayJobExpansion
}

// rayJobs implements RayJobInterface
type rayJobs struct {
	client rest.Interface
	ns     string
}

// newRayJobs returns a RayJobs
func newRayJobs(c *RayV1Client, namespace string) *rayJobs {
	return &rayJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rayJob, and returns the corresponding rayJob object, and an error if there is any.
func (c *rayJobs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RayJob, err error) {
	result = &v1.RayJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rayjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RayJobs that match those selectors.
func (c *rayJobs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RayJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.RayJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rayjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rayJobs.
func (c *rayJobs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rayjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rayJob and creates it.  Returns the server's representation of the rayJob, and an error, if there is any.
func (c *rayJobs) Create(ctx context.Context, rayJob *v1.RayJob, opts metav1.CreateOptions) (result *v1.RayJob, err error) {
	result = &v1.RayJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rayjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rayJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rayJob and updates it. Returns the server's representation of the rayJob, and an error, if there is any.
func (c *rayJobs) Update(ctx context.Context, rayJob *v1.RayJob, opts metav1.UpdateOptions) (result *v1.RayJob, err error) {
	result = &v1.RayJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rayjobs").
		Name(rayJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rayJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rayJobs) UpdateStatus(ctx context.Context, rayJob *v1.RayJob, opts metav1.UpdateOptions) (result *v1.RayJob, err error) {
	result = &v1.RayJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rayjobs").
		Name(rayJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rayJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rayJob and deletes it. Returns an error if one occurs.
func (c *rayJobs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rayjobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rayJobs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rayjobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rayJob.
func (c *rayJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RayJob, err error) {
	result = &v1.RayJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rayjobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied rayJob.
func (c *rayJobs) Apply(ctx context.Context, rayJob *rayv1.RayJobApplyConfiguration, opts metav1.ApplyOptions) (result *v1.RayJob, err error) {
	if rayJob == nil {
		return nil, fmt.Errorf("rayJob provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(rayJob)
	if err != nil {
		return nil, err
	}
	name := rayJob.Name
	if name == nil {
		return nil, fmt.Errorf("rayJob.Name must be provided to Apply")
	}
	result = &v1.RayJob{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("rayjobs").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *rayJobs) ApplyStatus(ctx context.Context, rayJob *rayv1.RayJobApplyConfiguration, opts metav1.ApplyOptions) (result *v1.RayJob, err error) {
	if rayJob == nil {
		return nil, fmt.Errorf("rayJob provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(rayJob)
	if err != nil {
		return nil, err
	}

	name := rayJob.Name
	if name == nil {
		return nil, fmt.Errorf("rayJob.Name must be provided to Apply")
	}

	result = &v1.RayJob{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("rayjobs").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
