{
 "title": "KubeRay Operator",
 "tags": [
  "Prometheus",
  "KubeRay Operator",
  "kube-state-metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{},namespace)"
    }
   },
   {
    "name": "Controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{namespace=\"$namespace\", pod=\"$ControllerPod\"},controller)"
    }
   },
   {
    "name": "ControllerPod",
    "query": {
     "query": "label_values(controller_runtime_active_workers{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controller Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Controller" },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "workqueue_depth{namespace=\"$namespace\", pod=\"$ControllerPod\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{namespace=\"$namespace\", pod=\"$ControllerPod\", controller=\"$Controller\"}[$__rate_interval])",
     "legendFormat": "{{controller}} - {{result}}"
    }
   ]
  },
  {
   "title": "Reconciling Latency Over Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_bucket{namespace=\"$namespace\", pod=\"$ControllerPod\", controller=\"$Controller\"}[$__rate_interval])) by (pod,le,controller)"
    }
   ]
  },
  {
   "title": "Reconciling Latency Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(controller_runtime_reconcile_time_seconds_bucket{namespace=\"$namespace\", pod=\"$ControllerPod\", controller=~\"$Controller\"}[$__rate_interval])) by (pod,le,controller))",
     "legendFormat": "{{controller}} - 50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{namespace=\"$namespace\", pod=\"$ControllerPod\", controller=~\"$Controller\"}[$__rate_interval])) by (pod,le,controller))",
     "legendFormat": "{{controller}} - 95%"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{namespace=\"$namespace\", pod=\"$ControllerPod\", controller=~\"$Controller\"}[$__rate_interval])) by (job,controller) / sum(rate(controller_runtime_reconcile_time_seconds_count{namespace=\"$namespace\", pod=\"$ControllerPod\", controller=~\"$Controller\"}[$__rate_interval])) by (job,controller)",
     "legendFormat": "{{controller}} - mean"
    }
   ]
  },
  {
   "title": "RayCluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace Resource Statistics",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kuberay_cluster_info) by (namespace)"
      }
     ]
    },
    {
     "title": "Provisioned Duration (Avg)",
     "type": "stat",
     "description": "Displays the average time it takes for RayClusters in the selected namespace(s) to transition their RayClusterProvisioned status from false (or unset) to true.",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kuberay_cluster_provisioned_duration_seconds{namespace=~\"$namespace\"})",
       "legendFormat": "Seconds"
      }
     ]
    },
    {
     "title": "Provisioned Duration ",
     "type": "table",
     "description": "Shows the time (in seconds) it took each RayCluster to become provisioned, grouped by name, namespace, and owner type.\n",
     "gridPos": { "h": 10, "w": 15, "x": 9, "y": 26 },
     "targets": [
      {
       "expr": "kuberay_cluster_info{namespace=~\"$namespace\"}"
      },
      {
       "expr": "kuberay_cluster_provisioned_duration_seconds{namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "RayClusterProvisioned (false)",
     "type": "table",
     "description": "Displays RayClusters in the selected namespace(s) that have not yet been provisioned (RayClusterProvisioned = false).",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "kuberay_cluster_condition_provisioned{namespace=~\"$namespace\", condition=~\"false\"}"
      }
     ]
    },
    {
     "title": "HeadPodReady (false)",
     "type": "table",
     "description": "Displays RayCluster head pods that are not ready.\n\n",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 36 },
     "targets": [
      {
       "expr": "kube_pod_status_ready{condition=\"false\", namespace=~\"$namespace\"} == 1 and on(pod) kube_pod_info{created_by_kind=\"RayCluster\", pod=~\".*-head\", namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "RayService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace Resource Statistics",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kuberay_service_info) by (namespace)"
      }
     ]
    },
    {
     "title": "RayServiceReady (false)",
     "type": "table",
     "description": "Displays RayServices in the selected namespace(s) that have not yet been ready (RayServiceReady = false).",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "kuberay_service_condition_ready{namespace=~\"$namespace\", condition=~\"false\"}"
      }
     ]
    },
    {
     "title": "UpgradeInProgress (true)",
     "type": "table",
     "description": "Displays RayServices in the selected namespace(s) that are currently performing a zero-downtime upgrade (UpgradeInProgress  = false)..",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 27 },
     "targets": [
      {
       "expr": "kuberay_service_condition_upgrade_in_progress{namespace=~\"$namespace\", condition=~\"true\"}"
      }
     ]
    }
   ]
  },
  { "title": "RayJob", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Namespace Resource Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kuberay_job_info) by (namespace)"
    }
   ]
  },
  {
   "title": "Execution Duration (Avg)",
   "type": "stat",
   "description": "Displays the average time duration from RayJob CR initialization to reaching a terminal state in the selected namespace(s)",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kuberay_job_execution_duration_seconds{namespace=~\"$namespace\"})",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Execution Duration ",
   "type": "table",
   "description": "\n",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "kuberay_job_execution_duration_seconds{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Deployment Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kuberay_job_deployment_status{namespace=~\"$namespace\"}) by (deployment_status)",
     "legendFormat": "{{deployment_status}}"
    }
   ]
  },
  {
   "title": "Deployment Status (Failed / Suspending / Suspended / Retrying / Waiting)",
   "type": "table",
   "description": "\n",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 38 },
   "targets": [
    {
     "expr": "kuberay_job_deployment_status{namespace=~\"$namespace\", deployment_status=~\"Failed|Suspending|Suspended|Retrying|Waiting\"}"
    }
   ]
  }
 ]
}