- label: 'Test Python Client'
  instance_size: large
  image: golang:1.24-bookworm
  commands:
    - source .buildkite/setup-env.sh
    - kind create cluster --wait 900s --config ./ci/kind-config-buildkite.yml
    - kubectl config set clusters.kind-kind.server https://docker:6443
    # Build nightly KubeRay operator image
    - pushd ray-operator
    - bash ../.buildkite/build-start-operator.sh
    - kubectl wait --timeout=90s --for=condition=Available=true deployment kuberay-operator
    - popd
    # Setup Python environment and install Python client
    - echo "--- START:Setting up Python environment"
    - pushd clients/python-client
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -e .
    - pip install pytest
    # Run Python client tests
    - echo "--- START:Running Python client tests"
    - set -o pipefail
    - pytest python_client_test/ -v || (kubectl logs --tail=50 -l app.kubernetes.io/name=kuberay && exit 1)
    - echo "--- END:Python client tests finished"
