// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	rayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
)

// AuthOptionsApplyConfiguration represents a declarative configuration of the AuthOptions type for use
// with apply.
type AuthOptionsApplyConfiguration struct {
	Mode *rayv1.AuthMode `json:"mode,omitempty"`
}

// AuthOptionsApplyConfiguration constructs a declarative configuration of the AuthOptions type for use with
// apply.
func AuthOptions() *AuthOptionsApplyConfiguration {
	return &AuthOptionsApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *AuthOptionsApplyConfiguration) WithMode(value rayv1.AuthMode) *AuthOptionsApplyConfiguration {
	b.Mode = &value
	return b
}
