// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	rayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
)

// AuthOptionsApplyConfiguration represents a declarative configuration of the AuthOptions type for use
// with apply.
//
// AuthOptions defines the authentication options for a RayCluster.
type AuthOptionsApplyConfiguration struct {
	// EnableK8sTokenAuth enables Kubernetes-delegated token authentication.
	// When true, the RAY_ENABLE_K8S_TOKEN_AUTH environment variable is set to "true"
	// across all Ray Pods, and Ray will delegate authentication to the K8s API server.
	//
	// NOTE: The Kubernetes ServiceAccount token mounted to Raylets must be granted
	// the `ray:write` custom verb via RBAC for this to function correctly.
	//
	// WARNING: This feature is intended for standalone RayCluster objects and is
	// currently unsupported for RayJob or RayService resources.
	EnableK8sTokenAuth *bool `json:"enableK8sTokenAuth,omitempty"`
	// Mode specifies the authentication mode.
	// Supported values are "disabled" and "token".
	// Defaults to "token".
	Mode *rayv1.AuthMode `json:"mode,omitempty"`
}

// AuthOptionsApplyConfiguration constructs a declarative configuration of the AuthOptions type for use with
// apply.
func AuthOptions() *AuthOptionsApplyConfiguration {
	return &AuthOptionsApplyConfiguration{}
}

// WithEnableK8sTokenAuth sets the EnableK8sTokenAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableK8sTokenAuth field is set to the value of the last call.
func (b *AuthOptionsApplyConfiguration) WithEnableK8sTokenAuth(value bool) *AuthOptionsApplyConfiguration {
	b.EnableK8sTokenAuth = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *AuthOptionsApplyConfiguration) WithMode(value rayv1.AuthMode) *AuthOptionsApplyConfiguration {
	b.Mode = &value
	return b
}
