// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// ClusterUpgradeOptionsApplyConfiguration represents a declarative configuration of the ClusterUpgradeOptions type for use
// with apply.
//
// These options are currently only supported for the IncrementalUpgrade type.
type ClusterUpgradeOptionsApplyConfiguration struct {
	// The capacity of serve requests the upgraded cluster should scale to handle each interval.
	// Defaults to 100%.
	MaxSurgePercent *int32 `json:"maxSurgePercent,omitempty"`
	// The percentage of traffic to switch to the upgraded RayCluster at a set interval after scaling by MaxSurgePercent.
	// StepSizePercent must be less than or equal to MaxSurgePercent.
	StepSizePercent *int32 `json:"stepSizePercent,omitempty"`
	// The interval in seconds between transferring StepSize traffic from the old to new RayCluster.
	IntervalSeconds *int32 `json:"intervalSeconds,omitempty"`
	// The name of the Gateway Class installed by the Kubernetes Cluster admin.
	GatewayClassName *string `json:"gatewayClassName,omitempty"`
	// GatewayAddresses is an optional list of addresses to set on the Gateway resource.
	// This is required on bare-metal clusters (e.g. MetalLB + Envoy Gateway) where the
	// Gateway implementation only becomes PROGRAMMED when spec.addresses is explicitly
	// provided. If empty, no addresses field is set on the Gateway (suitable for cloud
	// load-balancer environments that assign addresses automatically).
	GatewayAddresses []apisv1.GatewaySpecAddress `json:"gatewayAddresses,omitempty"`
}

// ClusterUpgradeOptionsApplyConfiguration constructs a declarative configuration of the ClusterUpgradeOptions type for use with
// apply.
func ClusterUpgradeOptions() *ClusterUpgradeOptionsApplyConfiguration {
	return &ClusterUpgradeOptionsApplyConfiguration{}
}

// WithMaxSurgePercent sets the MaxSurgePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSurgePercent field is set to the value of the last call.
func (b *ClusterUpgradeOptionsApplyConfiguration) WithMaxSurgePercent(value int32) *ClusterUpgradeOptionsApplyConfiguration {
	b.MaxSurgePercent = &value
	return b
}

// WithStepSizePercent sets the StepSizePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StepSizePercent field is set to the value of the last call.
func (b *ClusterUpgradeOptionsApplyConfiguration) WithStepSizePercent(value int32) *ClusterUpgradeOptionsApplyConfiguration {
	b.StepSizePercent = &value
	return b
}

// WithIntervalSeconds sets the IntervalSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IntervalSeconds field is set to the value of the last call.
func (b *ClusterUpgradeOptionsApplyConfiguration) WithIntervalSeconds(value int32) *ClusterUpgradeOptionsApplyConfiguration {
	b.IntervalSeconds = &value
	return b
}

// WithGatewayClassName sets the GatewayClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GatewayClassName field is set to the value of the last call.
func (b *ClusterUpgradeOptionsApplyConfiguration) WithGatewayClassName(value string) *ClusterUpgradeOptionsApplyConfiguration {
	b.GatewayClassName = &value
	return b
}

// WithGatewayAddresses adds the given value to the GatewayAddresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the GatewayAddresses field.
func (b *ClusterUpgradeOptionsApplyConfiguration) WithGatewayAddresses(values ...apisv1.GatewaySpecAddress) *ClusterUpgradeOptionsApplyConfiguration {
	for i := range values {
		b.GatewayAddresses = append(b.GatewayAddresses, values[i])
	}
	return b
}
