// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DeletionStrategyApplyConfiguration represents a declarative configuration of the DeletionStrategy type for use
// with apply.
//
// DeletionStrategy configures automated cleanup after the RayJob reaches a terminal state.
//
// Semantics:
// - The deletionRules list is the primary mechanism for cleanup; it must be non-empty when this block is present.
// - DeletionStrategy is mutually exclusive with spec.shutdownAfterJobFinishes.
// - Global spec.ttlSecondsAfterFinished > 0 requires shutdownAfterJobFinishes=true;
// therefore it cannot be used with DeletionStrategy (use condition.ttlSeconds within rules instead).
// - Feature gate RayJobDeletionPolicy must be enabled when this block is present.
//
// Validation:
// - Controller logic enforces rules vs shutdown exclusivity and TTL constraints.
// - Cross-field validation (CEL) ensures deletionRules is provided when the strategy is set.
type DeletionStrategyApplyConfiguration struct {
	// DeletionRules is a list of deletion rules, processed based on their trigger conditions.
	DeletionRules []DeletionRuleApplyConfiguration `json:"deletionRules,omitempty"`
	// OnSuccess is deprecated; use deletionRules instead.
	// This field is for backward compatibility but is no longer functional.
	OnSuccess *DeletionPolicyApplyConfiguration `json:"onSuccess,omitempty"`
	// OnFailure is deprecated; use deletionRules instead.
	// This field is for backward compatibility but is no longer functional.
	OnFailure *DeletionPolicyApplyConfiguration `json:"onFailure,omitempty"`
}

// DeletionStrategyApplyConfiguration constructs a declarative configuration of the DeletionStrategy type for use with
// apply.
func DeletionStrategy() *DeletionStrategyApplyConfiguration {
	return &DeletionStrategyApplyConfiguration{}
}

// WithDeletionRules adds the given value to the DeletionRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DeletionRules field.
func (b *DeletionStrategyApplyConfiguration) WithDeletionRules(values ...*DeletionRuleApplyConfiguration) *DeletionStrategyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDeletionRules")
		}
		b.DeletionRules = append(b.DeletionRules, *values[i])
	}
	return b
}

// WithOnSuccess sets the OnSuccess field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnSuccess field is set to the value of the last call.
func (b *DeletionStrategyApplyConfiguration) WithOnSuccess(value *DeletionPolicyApplyConfiguration) *DeletionStrategyApplyConfiguration {
	b.OnSuccess = value
	return b
}

// WithOnFailure sets the OnFailure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnFailure field is set to the value of the last call.
func (b *DeletionStrategyApplyConfiguration) WithOnFailure(value *DeletionPolicyApplyConfiguration) *DeletionStrategyApplyConfiguration {
	b.OnFailure = value
	return b
}
