// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	rayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
)

// DeletionConfigApplyConfiguration represents a declarative configuration of the DeletionConfig type for use
// with apply.
type DeletionConfigApplyConfiguration struct {
	Policy *rayv1.Policy `json:"policy,omitempty"`
}

// DeletionConfigApplyConfiguration constructs a declarative configuration of the DeletionConfig type for use with
// apply.
func DeletionConfig() *DeletionConfigApplyConfiguration {
	return &DeletionConfigApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *DeletionConfigApplyConfiguration) WithPolicy(value rayv1.Policy) *DeletionConfigApplyConfiguration {
	b.Policy = &value
	return b
}
