// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DeletionPolicyApplyConfiguration represents a declarative configuration of the DeletionPolicy type for use
// with apply.
type DeletionPolicyApplyConfiguration struct {
	OnSuccess *DeletionConfigApplyConfiguration `json:"onSuccess,omitempty"`
	OnFailure *DeletionConfigApplyConfiguration `json:"onFailure,omitempty"`
}

// DeletionPolicyApplyConfiguration constructs a declarative configuration of the DeletionPolicy type for use with
// apply.
func DeletionPolicy() *DeletionPolicyApplyConfiguration {
	return &DeletionPolicyApplyConfiguration{}
}

// WithOnSuccess sets the OnSuccess field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnSuccess field is set to the value of the last call.
func (b *DeletionPolicyApplyConfiguration) WithOnSuccess(value *DeletionConfigApplyConfiguration) *DeletionPolicyApplyConfiguration {
	b.OnSuccess = value
	return b
}

// WithOnFailure sets the OnFailure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnFailure field is set to the value of the last call.
func (b *DeletionPolicyApplyConfiguration) WithOnFailure(value *DeletionConfigApplyConfiguration) *DeletionPolicyApplyConfiguration {
	b.OnFailure = value
	return b
}
