// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GatewayReferenceApplyConfiguration represents a declarative configuration of the GatewayReference type for use
// with apply.
//
// GatewayReference references an existing Gateway resource. The controller only manages
// the HTTPRoute's backend weights on the referenced Gateway; HTTPRoute holds the
// route-level options that pin the HTTPRoute to a specific listener and scope the
// traffic it claims on a shared Gateway that KubeRay does not otherwise configure.
//
// The referenced Gateway must already exist and must allow HTTPRoutes from the
// RayService's namespace (its listeners' allowedRoutes). KubeRay never creates,
// updates, or deletes the referenced Gateway.
type GatewayReferenceApplyConfiguration struct {
	// Name of the existing Gateway. Must be a valid Gateway resource name
	// (an RFC 1123 subdomain).
	Name *string `json:"name,omitempty"`
	// Namespace of the existing Gateway. Defaults to the RayService's namespace when omitted.
	// Must be a valid namespace name (an RFC 1123 label).
	Namespace *string `json:"namespace,omitempty"`
	// HTTPRoute configures the HTTPRoute KubeRay attaches to the referenced Gateway:
	// which listener it attaches to and which traffic it claims. When omitted, the
	// HTTPRoute attaches to every listener that accepts it and matches all hostnames
	// with a "/" path prefix.
	HTTPRoute *GatewayHTTPRouteOptionsApplyConfiguration `json:"httpRoute,omitempty"`
}

// GatewayReferenceApplyConfiguration constructs a declarative configuration of the GatewayReference type for use with
// apply.
func GatewayReference() *GatewayReferenceApplyConfiguration {
	return &GatewayReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *GatewayReferenceApplyConfiguration) WithName(value string) *GatewayReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *GatewayReferenceApplyConfiguration) WithNamespace(value string) *GatewayReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithHTTPRoute sets the HTTPRoute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPRoute field is set to the value of the last call.
func (b *GatewayReferenceApplyConfiguration) WithHTTPRoute(value *GatewayHTTPRouteOptionsApplyConfiguration) *GatewayReferenceApplyConfiguration {
	b.HTTPRoute = value
	return b
}
