// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// GcsEmbeddedStorageApplyConfiguration represents a declarative configuration of the GcsEmbeddedStorage type for use
// with apply.
//
// GcsEmbeddedStorage configures the PVC backing the embedded RocksDB store.
type GcsEmbeddedStorageApplyConfiguration struct {
	// ExistingClaim, if set, makes the operator consume a user-provided PVC as-is
	// (no create, no delete, no ownerReferences). Mutually exclusive with
	// Size/StorageClassName/AccessModes.
	ExistingClaim *string `json:"existingClaim,omitempty"`
	// Size of the operator-managed PVC (e.g. "1Gi"). Ignored when ExistingClaim
	// is set. Defaults to 1Gi.
	Size *resource.Quantity `json:"size,omitempty"`
	// StorageClassName for the operator-managed PVC. Uses the cluster default
	// StorageClass when omitted.
	StorageClassName *string `json:"storageClassName,omitempty"`
	// AccessModes for the operator-managed PVC. Defaults to [ReadWriteOnce].
	AccessModes []corev1.PersistentVolumeAccessMode `json:"accessModes,omitempty"`
	// SubPath mounts a subdirectory of the volume instead of its root.
	SubPath *string `json:"subPath,omitempty"`
}

// GcsEmbeddedStorageApplyConfiguration constructs a declarative configuration of the GcsEmbeddedStorage type for use with
// apply.
func GcsEmbeddedStorage() *GcsEmbeddedStorageApplyConfiguration {
	return &GcsEmbeddedStorageApplyConfiguration{}
}

// WithExistingClaim sets the ExistingClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExistingClaim field is set to the value of the last call.
func (b *GcsEmbeddedStorageApplyConfiguration) WithExistingClaim(value string) *GcsEmbeddedStorageApplyConfiguration {
	b.ExistingClaim = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *GcsEmbeddedStorageApplyConfiguration) WithSize(value resource.Quantity) *GcsEmbeddedStorageApplyConfiguration {
	b.Size = &value
	return b
}

// WithStorageClassName sets the StorageClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClassName field is set to the value of the last call.
func (b *GcsEmbeddedStorageApplyConfiguration) WithStorageClassName(value string) *GcsEmbeddedStorageApplyConfiguration {
	b.StorageClassName = &value
	return b
}

// WithAccessModes adds the given value to the AccessModes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AccessModes field.
func (b *GcsEmbeddedStorageApplyConfiguration) WithAccessModes(values ...corev1.PersistentVolumeAccessMode) *GcsEmbeddedStorageApplyConfiguration {
	for i := range values {
		b.AccessModes = append(b.AccessModes, values[i])
	}
	return b
}

// WithSubPath sets the SubPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubPath field is set to the value of the last call.
func (b *GcsEmbeddedStorageApplyConfiguration) WithSubPath(value string) *GcsEmbeddedStorageApplyConfiguration {
	b.SubPath = &value
	return b
}
