// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	rayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
)

// GcsFaultToleranceOptionsApplyConfiguration represents a declarative configuration of the GcsFaultToleranceOptions type for use
// with apply.
//
// GcsFaultToleranceOptions contains configs for GCS FT
type GcsFaultToleranceOptionsApplyConfiguration struct {
	// Backend selects the GCS FT persistence backend. Defaults to "redis" for
	// backward compatibility. Immutable: the backend cannot be switched on an
	// existing RayCluster (doing so would swap the entire GCS store and head-Pod
	// wiring, losing fault-tolerance state).
	Backend                  *rayv1.GcsFaultToleranceBackend    `json:"backend,omitempty"`
	RedisUsername            *RedisCredentialApplyConfiguration `json:"redisUsername,omitempty"`
	RedisPassword            *RedisCredentialApplyConfiguration `json:"redisPassword,omitempty"`
	ExternalStorageNamespace *string                            `json:"externalStorageNamespace,omitempty"`
	// RedisAddress is the address of the external Redis service used when Backend
	// is "redis". It may alternatively be supplied via env vars/annotations.
	RedisAddress *string `json:"redisAddress,omitempty"`
	// Storage configures the persistent volume backing the embedded RocksDB
	// store. Only used when Backend is "rocksdb".
	Storage *GcsEmbeddedStorageApplyConfiguration `json:"storage,omitempty"`
	// EnableActivePassiveHead enables active-passive high availability for the GCS.
	// If enabled, KubeRay will provision a standby head node to ensure quick recovery.
	// EnableActivePassiveHead can be true only when Redis is configured (i.e. Backend
	// is "redis" and RedisAddress is set); it is not supported with the "rocksdb" backend.
	EnableActivePassiveHead *bool `json:"enableActivePassiveHead,omitempty"`
	// LeaderElectionLeaseDurationSeconds is the duration that non-leader candidates wait before forcing leadership acquisition.
	LeaderElectionLeaseDurationSeconds *int32 `json:"leaderElectionLeaseDurationSeconds,omitempty"`
	// LeaderElectionRenewDeadlineSeconds is the acting leader's bounded deadline for executing consecutive renewal sequences.
	LeaderElectionRenewDeadlineSeconds *int32 `json:"leaderElectionRenewDeadlineSeconds,omitempty"`
	// LeaderElectionRetryPeriodSeconds is the duration clients wait between sequential resource acquisition attempts.
	LeaderElectionRetryPeriodSeconds *int32 `json:"leaderElectionRetryPeriodSeconds,omitempty"`
}

// GcsFaultToleranceOptionsApplyConfiguration constructs a declarative configuration of the GcsFaultToleranceOptions type for use with
// apply.
func GcsFaultToleranceOptions() *GcsFaultToleranceOptionsApplyConfiguration {
	return &GcsFaultToleranceOptionsApplyConfiguration{}
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithBackend(value rayv1.GcsFaultToleranceBackend) *GcsFaultToleranceOptionsApplyConfiguration {
	b.Backend = &value
	return b
}

// WithRedisUsername sets the RedisUsername field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedisUsername field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithRedisUsername(value *RedisCredentialApplyConfiguration) *GcsFaultToleranceOptionsApplyConfiguration {
	b.RedisUsername = value
	return b
}

// WithRedisPassword sets the RedisPassword field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedisPassword field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithRedisPassword(value *RedisCredentialApplyConfiguration) *GcsFaultToleranceOptionsApplyConfiguration {
	b.RedisPassword = value
	return b
}

// WithExternalStorageNamespace sets the ExternalStorageNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalStorageNamespace field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithExternalStorageNamespace(value string) *GcsFaultToleranceOptionsApplyConfiguration {
	b.ExternalStorageNamespace = &value
	return b
}

// WithRedisAddress sets the RedisAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedisAddress field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithRedisAddress(value string) *GcsFaultToleranceOptionsApplyConfiguration {
	b.RedisAddress = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithStorage(value *GcsEmbeddedStorageApplyConfiguration) *GcsFaultToleranceOptionsApplyConfiguration {
	b.Storage = value
	return b
}

// WithEnableActivePassiveHead sets the EnableActivePassiveHead field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableActivePassiveHead field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithEnableActivePassiveHead(value bool) *GcsFaultToleranceOptionsApplyConfiguration {
	b.EnableActivePassiveHead = &value
	return b
}

// WithLeaderElectionLeaseDurationSeconds sets the LeaderElectionLeaseDurationSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderElectionLeaseDurationSeconds field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithLeaderElectionLeaseDurationSeconds(value int32) *GcsFaultToleranceOptionsApplyConfiguration {
	b.LeaderElectionLeaseDurationSeconds = &value
	return b
}

// WithLeaderElectionRenewDeadlineSeconds sets the LeaderElectionRenewDeadlineSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderElectionRenewDeadlineSeconds field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithLeaderElectionRenewDeadlineSeconds(value int32) *GcsFaultToleranceOptionsApplyConfiguration {
	b.LeaderElectionRenewDeadlineSeconds = &value
	return b
}

// WithLeaderElectionRetryPeriodSeconds sets the LeaderElectionRetryPeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderElectionRetryPeriodSeconds field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithLeaderElectionRetryPeriodSeconds(value int32) *GcsFaultToleranceOptionsApplyConfiguration {
	b.LeaderElectionRetryPeriodSeconds = &value
	return b
}
