// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	rayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
)

// GcsFaultToleranceOptionsApplyConfiguration represents a declarative configuration of the GcsFaultToleranceOptions type for use
// with apply.
//
// GcsFaultToleranceOptions contains configs for GCS FT
type GcsFaultToleranceOptionsApplyConfiguration struct {
	// Backend selects the GCS FT persistence backend. Defaults to "redis" for
	// backward compatibility.
	Backend                  *rayv1.GcsFaultToleranceBackend    `json:"backend,omitempty"`
	RedisUsername            *RedisCredentialApplyConfiguration `json:"redisUsername,omitempty"`
	RedisPassword            *RedisCredentialApplyConfiguration `json:"redisPassword,omitempty"`
	ExternalStorageNamespace *string                            `json:"externalStorageNamespace,omitempty"`
	// RedisAddress is required when Backend is "redis" (enforced by validation).
	RedisAddress *string `json:"redisAddress,omitempty"`
	// Storage configures the persistent volume backing the embedded RocksDB
	// store. Only used when Backend is "rocksdb".
	Storage *GcsEmbeddedStorageApplyConfiguration `json:"storage,omitempty"`
}

// GcsFaultToleranceOptionsApplyConfiguration constructs a declarative configuration of the GcsFaultToleranceOptions type for use with
// apply.
func GcsFaultToleranceOptions() *GcsFaultToleranceOptionsApplyConfiguration {
	return &GcsFaultToleranceOptionsApplyConfiguration{}
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithBackend(value rayv1.GcsFaultToleranceBackend) *GcsFaultToleranceOptionsApplyConfiguration {
	b.Backend = &value
	return b
}

// WithRedisUsername sets the RedisUsername field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedisUsername field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithRedisUsername(value *RedisCredentialApplyConfiguration) *GcsFaultToleranceOptionsApplyConfiguration {
	b.RedisUsername = value
	return b
}

// WithRedisPassword sets the RedisPassword field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedisPassword field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithRedisPassword(value *RedisCredentialApplyConfiguration) *GcsFaultToleranceOptionsApplyConfiguration {
	b.RedisPassword = value
	return b
}

// WithExternalStorageNamespace sets the ExternalStorageNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalStorageNamespace field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithExternalStorageNamespace(value string) *GcsFaultToleranceOptionsApplyConfiguration {
	b.ExternalStorageNamespace = &value
	return b
}

// WithRedisAddress sets the RedisAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedisAddress field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithRedisAddress(value string) *GcsFaultToleranceOptionsApplyConfiguration {
	b.RedisAddress = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *GcsFaultToleranceOptionsApplyConfiguration) WithStorage(value *GcsEmbeddedStorageApplyConfiguration) *GcsFaultToleranceOptionsApplyConfiguration {
	b.Storage = value
	return b
}
