// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// GcsReadyOptionsApplyConfiguration represents a declarative configuration of the GcsReadyOptions type for use
// with apply.
//
// GcsReadyOptions specifies optional configuration for the GCS-readiness init container (wait-gcs-ready).
type GcsReadyOptionsApplyConfiguration struct {
	// Resources overrides the resource requests and limits of the wait-gcs-ready init container.
	// Default values: 200m CPU request and limit. 256Mi memory request and limit.
	Resources *corev1.ResourceRequirements `json:"resources,omitempty"`
}

// GcsReadyOptionsApplyConfiguration constructs a declarative configuration of the GcsReadyOptions type for use with
// apply.
func GcsReadyOptions() *GcsReadyOptionsApplyConfiguration {
	return &GcsReadyOptionsApplyConfiguration{}
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *GcsReadyOptionsApplyConfiguration) WithResources(value corev1.ResourceRequirements) *GcsReadyOptionsApplyConfiguration {
	b.Resources = &value
	return b
}
