// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GracefulTerminationOptionsApplyConfiguration represents a declarative configuration of the GracefulTerminationOptions type for use
// with apply.
//
// GracefulTerminationOptions contains configs for graceful Pod termination.
type GracefulTerminationOptionsApplyConfiguration struct {
	// TerminationGracePeriodSeconds is set on the head and worker Pod specs
	// if not already specified by the user's own pod template. Defaults to
	// 30 seconds if unset.
	TerminationGracePeriodSeconds *int64 `json:"terminationGracePeriodSeconds,omitempty"`
	// DrainDeadlineSeconds is passed to `ray drain-node` as
	// `--deadline-remaining-seconds`, an advisory deadline for Ray's own
	// scheduler (Ray does not self-enforce it; Kubernetes'
	// terminationGracePeriodSeconds is what actually bounds the wait).
	// Defaults to TerminationGracePeriodSeconds if unset.
	DrainDeadlineSeconds *int64 `json:"drainDeadlineSeconds,omitempty"`
}

// GracefulTerminationOptionsApplyConfiguration constructs a declarative configuration of the GracefulTerminationOptions type for use with
// apply.
func GracefulTerminationOptions() *GracefulTerminationOptionsApplyConfiguration {
	return &GracefulTerminationOptionsApplyConfiguration{}
}

// WithTerminationGracePeriodSeconds sets the TerminationGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminationGracePeriodSeconds field is set to the value of the last call.
func (b *GracefulTerminationOptionsApplyConfiguration) WithTerminationGracePeriodSeconds(value int64) *GracefulTerminationOptionsApplyConfiguration {
	b.TerminationGracePeriodSeconds = &value
	return b
}

// WithDrainDeadlineSeconds sets the DrainDeadlineSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DrainDeadlineSeconds field is set to the value of the last call.
func (b *GracefulTerminationOptionsApplyConfiguration) WithDrainDeadlineSeconds(value int64) *GracefulTerminationOptionsApplyConfiguration {
	b.DrainDeadlineSeconds = &value
	return b
}
