// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// IngressTLSConfigApplyConfiguration represents a declarative configuration of the IngressTLSConfig type for use
// with apply.
//
// IngressTLSConfig defines a TLS entry for the generated ingress.
type IngressTLSConfigApplyConfiguration struct {
	// Hosts is a list of hosts included in the TLS certificate.
	Hosts []string `json:"hosts,omitempty"`
	// SecretName is the name of the secret used to terminate TLS.
	SecretName *string `json:"secretName,omitempty"`
}

// IngressTLSConfigApplyConfiguration constructs a declarative configuration of the IngressTLSConfig type for use with
// apply.
func IngressTLSConfig() *IngressTLSConfigApplyConfiguration {
	return &IngressTLSConfigApplyConfiguration{}
}

// WithHosts adds the given value to the Hosts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Hosts field.
func (b *IngressTLSConfigApplyConfiguration) WithHosts(values ...string) *IngressTLSConfigApplyConfiguration {
	for i := range values {
		b.Hosts = append(b.Hosts, values[i])
	}
	return b
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *IngressTLSConfigApplyConfiguration) WithSecretName(value string) *IngressTLSConfigApplyConfiguration {
	b.SecretName = &value
	return b
}
