// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NodeLabelMappingApplyConfiguration represents a declarative configuration of the NodeLabelMapping type for use
// with apply.
//
// NodeLabelMapping maps one Kubernetes node label to a Ray node label.
type NodeLabelMappingApplyConfiguration struct {
	// NodeLabel is the node label key to read. Must be in the operator's allowedNodeLabels.
	NodeLabel *string `json:"nodeLabel,omitempty"`
	// MapTo is the Ray label key to deliver the value under. If empty, defaults to the value of nodeLabel.
	// The keys set here should not conflict with the workerGroupSpec.Labels, since --labels overwrites --labels-file.
	MapTo *string `json:"mapTo,omitempty"`
}

// NodeLabelMappingApplyConfiguration constructs a declarative configuration of the NodeLabelMapping type for use with
// apply.
func NodeLabelMapping() *NodeLabelMappingApplyConfiguration {
	return &NodeLabelMappingApplyConfiguration{}
}

// WithNodeLabel sets the NodeLabel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeLabel field is set to the value of the last call.
func (b *NodeLabelMappingApplyConfiguration) WithNodeLabel(value string) *NodeLabelMappingApplyConfiguration {
	b.NodeLabel = &value
	return b
}

// WithMapTo sets the MapTo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MapTo field is set to the value of the last call.
func (b *NodeLabelMappingApplyConfiguration) WithMapTo(value string) *NodeLabelMappingApplyConfiguration {
	b.MapTo = &value
	return b
}
