// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// RayClusterSpecApplyConfiguration represents a declarative configuration of the RayClusterSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// RayClusterSpec defines the desired state of RayCluster
type RayClusterSpecApplyConfiguration struct {
	// UpgradeStrategy defines the scaling policy used when upgrading the RayCluster
	UpgradeStrategy *RayClusterUpgradeStrategyApplyConfiguration `json:"upgradeStrategy,omitempty"`
	// AuthOptions specifies the authentication options for the RayCluster.
	AuthOptions *AuthOptionsApplyConfiguration `json:"authOptions,omitempty"`
	// Suspend indicates whether a RayCluster should be suspended.
	// A suspended RayCluster will have head pods and worker pods deleted.
	Suspend *bool `json:"suspend,omitempty"`
	// ManagedBy is an optional configuration for the controller or entity that manages a RayCluster.
	// The value must be either 'ray.io/kuberay-operator' or 'kueue.x-k8s.io/multikueue'.
	// The kuberay-operator reconciles a RayCluster which doesn't have this field at all or
	// the field value is the reserved string 'ray.io/kuberay-operator',
	// but delegates reconciling the RayCluster with 'kueue.x-k8s.io/multikueue' to the Kueue.
	// The field is immutable.
	ManagedBy *string `json:"managedBy,omitempty"`
	// AutoscalerOptions specifies optional configuration for the Ray autoscaler.
	AutoscalerOptions      *AutoscalerOptionsApplyConfiguration `json:"autoscalerOptions,omitempty"`
	HeadServiceAnnotations map[string]string                    `json:"headServiceAnnotations,omitempty"`
	// EnableInTreeAutoscaling indicates whether operator should create in tree autoscaling configs
	EnableInTreeAutoscaling *bool `json:"enableInTreeAutoscaling,omitempty"`
	// GcsFaultToleranceOptions for enabling GCS FT
	GcsFaultToleranceOptions *GcsFaultToleranceOptionsApplyConfiguration `json:"gcsFaultToleranceOptions,omitempty"`
	// HeadGroupSpec is the spec for the head pod
	HeadGroupSpec *HeadGroupSpecApplyConfiguration `json:"headGroupSpec,omitempty"`
	// RayVersion is used to determine the command for the Kubernetes Job managed by RayJob
	RayVersion *string `json:"rayVersion,omitempty"`
	// WorkerGroupSpecs are the specs for the worker pods
	WorkerGroupSpecs []WorkerGroupSpecApplyConfiguration `json:"workerGroupSpecs,omitempty"`
}

// RayClusterSpecApplyConfiguration constructs a declarative configuration of the RayClusterSpec type for use with
// apply.
func RayClusterSpec() *RayClusterSpecApplyConfiguration {
	return &RayClusterSpecApplyConfiguration{}
}

// WithUpgradeStrategy sets the UpgradeStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpgradeStrategy field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithUpgradeStrategy(value *RayClusterUpgradeStrategyApplyConfiguration) *RayClusterSpecApplyConfiguration {
	b.UpgradeStrategy = value
	return b
}

// WithAuthOptions sets the AuthOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthOptions field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithAuthOptions(value *AuthOptionsApplyConfiguration) *RayClusterSpecApplyConfiguration {
	b.AuthOptions = value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithSuspend(value bool) *RayClusterSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithManagedBy sets the ManagedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagedBy field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithManagedBy(value string) *RayClusterSpecApplyConfiguration {
	b.ManagedBy = &value
	return b
}

// WithAutoscalerOptions sets the AutoscalerOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoscalerOptions field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithAutoscalerOptions(value *AutoscalerOptionsApplyConfiguration) *RayClusterSpecApplyConfiguration {
	b.AutoscalerOptions = value
	return b
}

// WithHeadServiceAnnotations puts the entries into the HeadServiceAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the HeadServiceAnnotations field,
// overwriting an existing map entries in HeadServiceAnnotations field with the same key.
func (b *RayClusterSpecApplyConfiguration) WithHeadServiceAnnotations(entries map[string]string) *RayClusterSpecApplyConfiguration {
	if b.HeadServiceAnnotations == nil && len(entries) > 0 {
		b.HeadServiceAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.HeadServiceAnnotations[k] = v
	}
	return b
}

// WithEnableInTreeAutoscaling sets the EnableInTreeAutoscaling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableInTreeAutoscaling field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithEnableInTreeAutoscaling(value bool) *RayClusterSpecApplyConfiguration {
	b.EnableInTreeAutoscaling = &value
	return b
}

// WithGcsFaultToleranceOptions sets the GcsFaultToleranceOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GcsFaultToleranceOptions field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithGcsFaultToleranceOptions(value *GcsFaultToleranceOptionsApplyConfiguration) *RayClusterSpecApplyConfiguration {
	b.GcsFaultToleranceOptions = value
	return b
}

// WithHeadGroupSpec sets the HeadGroupSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeadGroupSpec field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithHeadGroupSpec(value *HeadGroupSpecApplyConfiguration) *RayClusterSpecApplyConfiguration {
	b.HeadGroupSpec = value
	return b
}

// WithRayVersion sets the RayVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RayVersion field is set to the value of the last call.
func (b *RayClusterSpecApplyConfiguration) WithRayVersion(value string) *RayClusterSpecApplyConfiguration {
	b.RayVersion = &value
	return b
}

// WithWorkerGroupSpecs adds the given value to the WorkerGroupSpecs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WorkerGroupSpecs field.
func (b *RayClusterSpecApplyConfiguration) WithWorkerGroupSpecs(values ...*WorkerGroupSpecApplyConfiguration) *RayClusterSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWorkerGroupSpecs")
		}
		b.WorkerGroupSpecs = append(b.WorkerGroupSpecs, *values[i])
	}
	return b
}
