// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RayClusterConditionApplyConfiguration represents an declarative configuration of the RayClusterCondition type for use
// with apply.
type RayClusterConditionApplyConfiguration struct {
	Type               *v1.RayClusterConditionType `json:"type,omitempty"`
	Status             *corev1.ConditionStatus     `json:"status,omitempty"`
	LastUpdateTime     *metav1.Time                `json:"lastUpdateTime,omitempty"`
	LastTransitionTime *metav1.Time                `json:"lastTransitionTime,omitempty"`
	Reason             *string                     `json:"reason,omitempty"`
	Message            *string                     `json:"message,omitempty"`
}

// RayClusterConditionApplyConfiguration constructs an declarative configuration of the RayClusterCondition type for use with
// apply.
func RayClusterCondition() *RayClusterConditionApplyConfiguration {
	return &RayClusterConditionApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RayClusterConditionApplyConfiguration) WithType(value v1.RayClusterConditionType) *RayClusterConditionApplyConfiguration {
	b.Type = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *RayClusterConditionApplyConfiguration) WithStatus(value corev1.ConditionStatus) *RayClusterConditionApplyConfiguration {
	b.Status = &value
	return b
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *RayClusterConditionApplyConfiguration) WithLastUpdateTime(value metav1.Time) *RayClusterConditionApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *RayClusterConditionApplyConfiguration) WithLastTransitionTime(value metav1.Time) *RayClusterConditionApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *RayClusterConditionApplyConfiguration) WithReason(value string) *RayClusterConditionApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *RayClusterConditionApplyConfiguration) WithMessage(value string) *RayClusterConditionApplyConfiguration {
	b.Message = &value
	return b
}
