// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// RayCronJobSpecApplyConfiguration represents a declarative configuration of the RayCronJobSpec type for use
// with apply.
type RayCronJobSpecApplyConfiguration struct {
	JobTemplate *RayJobSpecApplyConfiguration `json:"jobTemplate,omitempty"`
	Schedule    *string                       `json:"schedule,omitempty"`
	Suspend     *bool                         `json:"suspend,omitempty"`
}

// RayCronJobSpecApplyConfiguration constructs a declarative configuration of the RayCronJobSpec type for use with
// apply.
func RayCronJobSpec() *RayCronJobSpecApplyConfiguration {
	return &RayCronJobSpecApplyConfiguration{}
}

// WithJobTemplate sets the JobTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobTemplate field is set to the value of the last call.
func (b *RayCronJobSpecApplyConfiguration) WithJobTemplate(value *RayJobSpecApplyConfiguration) *RayCronJobSpecApplyConfiguration {
	b.JobTemplate = value
	return b
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *RayCronJobSpecApplyConfiguration) WithSchedule(value string) *RayCronJobSpecApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *RayCronJobSpecApplyConfiguration) WithSuspend(value bool) *RayCronJobSpecApplyConfiguration {
	b.Suspend = &value
	return b
}
