// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	rayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
)

// TLSOptionsApplyConfiguration represents a declarative configuration of the TLSOptions type for use
// with apply.
//
// TLSOptions configures TLS encryption for the RayCluster.
// When TLSOptions is nil, TLS is disabled. When set, the operator uses
// cert-manager to automatically provision a full PKI (self-signed CA, head
// and worker leaf certificates) and keeps certificates up to date as pod IPs
// change during autoscaling.
type TLSOptionsApplyConfiguration struct {
	// Mode selects the TLS security mode.
	// Supported values: "MutualTLS" (mutual TLS, client & server authentication).
	// Defaults to "MutualTLS".
	Mode *rayv1.TLSMode `json:"mode,omitempty"`
}

// TLSOptionsApplyConfiguration constructs a declarative configuration of the TLSOptions type for use with
// apply.
func TLSOptions() *TLSOptionsApplyConfiguration {
	return &TLSOptionsApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *TLSOptionsApplyConfiguration) WithMode(value rayv1.TLSMode) *TLSOptionsApplyConfiguration {
	b.Mode = &value
	return b
}
