// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "k8s.io/api/networking/v1"
)

// WorkerGroupNetworkPolicyRulesApplyConfiguration represents a declarative configuration of the WorkerGroupNetworkPolicyRules type for use
// with apply.
//
// WorkerGroupNetworkPolicyRules is NetworkPolicyRules bound to one worker group.
type WorkerGroupNetworkPolicyRulesApplyConfiguration struct {
	// GroupName matches WorkerGroupSpec.GroupName.
	GroupName                            *string `json:"groupName,omitempty"`
	NetworkPolicyRulesApplyConfiguration `json:",inline"`
}

// WorkerGroupNetworkPolicyRulesApplyConfiguration constructs a declarative configuration of the WorkerGroupNetworkPolicyRules type for use with
// apply.
func WorkerGroupNetworkPolicyRules() *WorkerGroupNetworkPolicyRulesApplyConfiguration {
	return &WorkerGroupNetworkPolicyRulesApplyConfiguration{}
}

// WithGroupName sets the GroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupName field is set to the value of the last call.
func (b *WorkerGroupNetworkPolicyRulesApplyConfiguration) WithGroupName(value string) *WorkerGroupNetworkPolicyRulesApplyConfiguration {
	b.GroupName = &value
	return b
}

// WithIngressRules adds the given value to the IngressRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IngressRules field.
func (b *WorkerGroupNetworkPolicyRulesApplyConfiguration) WithIngressRules(values ...networkingv1.NetworkPolicyIngressRule) *WorkerGroupNetworkPolicyRulesApplyConfiguration {
	for i := range values {
		b.NetworkPolicyRulesApplyConfiguration.IngressRules = append(b.NetworkPolicyRulesApplyConfiguration.IngressRules, values[i])
	}
	return b
}

// WithEgressRules adds the given value to the EgressRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EgressRules field.
func (b *WorkerGroupNetworkPolicyRulesApplyConfiguration) WithEgressRules(values ...networkingv1.NetworkPolicyEgressRule) *WorkerGroupNetworkPolicyRulesApplyConfiguration {
	for i := range values {
		b.NetworkPolicyRulesApplyConfiguration.EgressRules = append(b.NetworkPolicyRulesApplyConfiguration.EgressRules, values[i])
	}
	return b
}
