apiVersion: v2
name: kuberay-operator
description: A Helm chart for deploying the Kuberay operator on Kubernetes.
version: 2.0.0
appVersion: v1.7.1
type: application
keywords:
  - ray
  - ray operator
  - distributed computing
  - data processing
  - machine learning
  - deep learning
  - hyperparameter tuning
  - reinforcement learning
  - model serving
home: https://github.com/ray-project/kuberay
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  application.giantswarm.io/team: planeteers
  io.giantswarm.application.audience: all
  io.giantswarm.application.team: planeteers
