{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ray-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ray-cluster.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      ray.io/cluster: {{ include "ray-cluster.fullname" . }}
      {{- with .Values.podDisruptionBudget.selectorLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
