package types

// EventType is the Ray event type.
type EventType string

// There are 11 potential Ray event types:
// https://github.com/ray-project/ray/blob/3b41c97fa90c58b0b72c0026f57005b92310160d/src/ray/protobuf/public/events_base_event.proto#L49-L61
const (
	EVENT_TYPE_UNSPECIFIED      EventType = "EVENT_TYPE_UNSPECIFIED"
	TASK_DEFINITION_EVENT       EventType = "TASK_DEFINITION_EVENT"
	TASK_LIFECYCLE_EVENT        EventType = "TASK_LIFECYCLE_EVENT"
	ACTOR_TASK_DEFINITION_EVENT EventType = "ACTOR_TASK_DEFINITION_EVENT"
	TASK_PROFILE_EVENT          EventType = "TASK_PROFILE_EVENT"
	DRIVER_JOB_DEFINITION_EVENT EventType = "DRIVER_JOB_DEFINITION_EVENT"
	DRIVER_JOB_LIFECYCLE_EVENT  EventType = "DRIVER_JOB_LIFECYCLE_EVENT"
	NODE_DEFINITION_EVENT       EventType = "NODE_DEFINITION_EVENT"
	NODE_LIFECYCLE_EVENT        EventType = "NODE_LIFECYCLE_EVENT"
	ACTOR_DEFINITION_EVENT      EventType = "ACTOR_DEFINITION_EVENT"
	ACTOR_LIFECYCLE_EVENT       EventType = "ACTOR_LIFECYCLE_EVENT"
)

// AllEventTypes includes all potential event types defined in Ray.
var AllEventTypes = []EventType{
	EVENT_TYPE_UNSPECIFIED,
	TASK_DEFINITION_EVENT,
	TASK_LIFECYCLE_EVENT,
	ACTOR_TASK_DEFINITION_EVENT,
	TASK_PROFILE_EVENT,
	DRIVER_JOB_DEFINITION_EVENT,
	DRIVER_JOB_LIFECYCLE_EVENT,
	NODE_DEFINITION_EVENT,
	NODE_LIFECYCLE_EVENT,
	ACTOR_DEFINITION_EVENT,
	ACTOR_LIFECYCLE_EVENT,
}
