package types

type EventType string

const (
	EVENT_TYPE_UNSPECIFIED      EventType = "EVENT_TYPE_UNSPECIFIED"
	TASK_DEFINITION_EVENT       EventType = "TASK_DEFINITION_EVENT"
	TASK_LIFECYCLE_EVENT        EventType = "TASK_LIFECYCLE_EVENT"
	ACTOR_TASK_DEFINITION_EVENT EventType = "ACTOR_TASK_DEFINITION_EVENT"
	TASK_PROFILE_EVENT          EventType = "TASK_PROFILE_EVENT"
	DRIVER_JOB_DEFINITION_EVENT EventType = "DRIVER_JOB_DEFINITION_EVENT"
	DRIVER_JOB_LIFECYCLE_EVENT  EventType = "DRIVER_JOB_LIFECYCLE_EVENT"
	NODE_DEFINITION_EVENT       EventType = "NODE_DEFINITION_EVENT"
	NODE_LIFECYCLE_EVENT        EventType = "NODE_LIFECYCLE_EVENT"
	ACTOR_DEFINITION_EVENT      EventType = "ACTOR_DEFINITION_EVENT"
	ACTOR_LIFECYCLE_EVENT       EventType = "ACTOR_LIFECYCLE_EVENT"
)
