//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1alpha1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AppStatus)(nil), (*v1alpha1.AppStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AppStatus_To_v1alpha1_AppStatus(a.(*AppStatus), b.(*v1alpha1.AppStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AppStatus)(nil), (*AppStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppStatus_To_v1beta1_AppStatus(a.(*v1alpha1.AppStatus), b.(*AppStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AutoscalerOptions)(nil), (*v1alpha1.AutoscalerOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AutoscalerOptions_To_v1alpha1_AutoscalerOptions(a.(*AutoscalerOptions), b.(*v1alpha1.AutoscalerOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.AutoscalerOptions)(nil), (*AutoscalerOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AutoscalerOptions_To_v1beta1_AutoscalerOptions(a.(*v1alpha1.AutoscalerOptions), b.(*AutoscalerOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DashboardStatus)(nil), (*v1alpha1.DashboardStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DashboardStatus_To_v1alpha1_DashboardStatus(a.(*DashboardStatus), b.(*v1alpha1.DashboardStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DashboardStatus)(nil), (*DashboardStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DashboardStatus_To_v1beta1_DashboardStatus(a.(*v1alpha1.DashboardStatus), b.(*DashboardStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HeadGroupSpec)(nil), (*v1alpha1.HeadGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HeadGroupSpec_To_v1alpha1_HeadGroupSpec(a.(*HeadGroupSpec), b.(*v1alpha1.HeadGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.HeadGroupSpec)(nil), (*HeadGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HeadGroupSpec_To_v1beta1_HeadGroupSpec(a.(*v1alpha1.HeadGroupSpec), b.(*HeadGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HeadInfo)(nil), (*v1alpha1.HeadInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HeadInfo_To_v1alpha1_HeadInfo(a.(*HeadInfo), b.(*v1alpha1.HeadInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.HeadInfo)(nil), (*HeadInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HeadInfo_To_v1beta1_HeadInfo(a.(*v1alpha1.HeadInfo), b.(*HeadInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayActorOptionSpec)(nil), (*v1alpha1.RayActorOptionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayActorOptionSpec_To_v1alpha1_RayActorOptionSpec(a.(*RayActorOptionSpec), b.(*v1alpha1.RayActorOptionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayActorOptionSpec)(nil), (*RayActorOptionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayActorOptionSpec_To_v1beta1_RayActorOptionSpec(a.(*v1alpha1.RayActorOptionSpec), b.(*RayActorOptionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayCluster)(nil), (*v1alpha1.RayCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayCluster_To_v1alpha1_RayCluster(a.(*RayCluster), b.(*v1alpha1.RayCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayCluster)(nil), (*RayCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayCluster_To_v1beta1_RayCluster(a.(*v1alpha1.RayCluster), b.(*RayCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayClusterList)(nil), (*v1alpha1.RayClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayClusterList_To_v1alpha1_RayClusterList(a.(*RayClusterList), b.(*v1alpha1.RayClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayClusterList)(nil), (*RayClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayClusterList_To_v1beta1_RayClusterList(a.(*v1alpha1.RayClusterList), b.(*RayClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayClusterSpec)(nil), (*v1alpha1.RayClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayClusterSpec_To_v1alpha1_RayClusterSpec(a.(*RayClusterSpec), b.(*v1alpha1.RayClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayClusterSpec)(nil), (*RayClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayClusterSpec_To_v1beta1_RayClusterSpec(a.(*v1alpha1.RayClusterSpec), b.(*RayClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayClusterStatus)(nil), (*v1alpha1.RayClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayClusterStatus_To_v1alpha1_RayClusterStatus(a.(*RayClusterStatus), b.(*v1alpha1.RayClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayClusterStatus)(nil), (*RayClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayClusterStatus_To_v1beta1_RayClusterStatus(a.(*v1alpha1.RayClusterStatus), b.(*RayClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayService)(nil), (*v1alpha1.RayService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayService_To_v1alpha1_RayService(a.(*RayService), b.(*v1alpha1.RayService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayService)(nil), (*RayService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayService_To_v1beta1_RayService(a.(*v1alpha1.RayService), b.(*RayService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayServiceList)(nil), (*v1alpha1.RayServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayServiceList_To_v1alpha1_RayServiceList(a.(*RayServiceList), b.(*v1alpha1.RayServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayServiceList)(nil), (*RayServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayServiceList_To_v1beta1_RayServiceList(a.(*v1alpha1.RayServiceList), b.(*RayServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayServiceSpec)(nil), (*v1alpha1.RayServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayServiceSpec_To_v1alpha1_RayServiceSpec(a.(*RayServiceSpec), b.(*v1alpha1.RayServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayServiceSpec)(nil), (*RayServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayServiceSpec_To_v1beta1_RayServiceSpec(a.(*v1alpha1.RayServiceSpec), b.(*RayServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayServiceStatus)(nil), (*v1alpha1.RayServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayServiceStatus_To_v1alpha1_RayServiceStatus(a.(*RayServiceStatus), b.(*v1alpha1.RayServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayServiceStatus)(nil), (*RayServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayServiceStatus_To_v1beta1_RayServiceStatus(a.(*v1alpha1.RayServiceStatus), b.(*RayServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RayServiceStatuses)(nil), (*v1alpha1.RayServiceStatuses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RayServiceStatuses_To_v1alpha1_RayServiceStatuses(a.(*RayServiceStatuses), b.(*v1alpha1.RayServiceStatuses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RayServiceStatuses)(nil), (*RayServiceStatuses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RayServiceStatuses_To_v1beta1_RayServiceStatuses(a.(*v1alpha1.RayServiceStatuses), b.(*RayServiceStatuses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ScaleStrategy)(nil), (*v1alpha1.ScaleStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ScaleStrategy_To_v1alpha1_ScaleStrategy(a.(*ScaleStrategy), b.(*v1alpha1.ScaleStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ScaleStrategy)(nil), (*ScaleStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ScaleStrategy_To_v1beta1_ScaleStrategy(a.(*v1alpha1.ScaleStrategy), b.(*ScaleStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServeConfigSpec)(nil), (*v1alpha1.ServeConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ServeConfigSpec_To_v1alpha1_ServeConfigSpec(a.(*ServeConfigSpec), b.(*v1alpha1.ServeConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServeConfigSpec)(nil), (*ServeConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServeConfigSpec_To_v1beta1_ServeConfigSpec(a.(*v1alpha1.ServeConfigSpec), b.(*ServeConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServeDeploymentGraphSpec)(nil), (*v1alpha1.ServeDeploymentGraphSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ServeDeploymentGraphSpec_To_v1alpha1_ServeDeploymentGraphSpec(a.(*ServeDeploymentGraphSpec), b.(*v1alpha1.ServeDeploymentGraphSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServeDeploymentGraphSpec)(nil), (*ServeDeploymentGraphSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServeDeploymentGraphSpec_To_v1beta1_ServeDeploymentGraphSpec(a.(*v1alpha1.ServeDeploymentGraphSpec), b.(*ServeDeploymentGraphSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServeDeploymentStatus)(nil), (*v1alpha1.ServeDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ServeDeploymentStatus_To_v1alpha1_ServeDeploymentStatus(a.(*ServeDeploymentStatus), b.(*v1alpha1.ServeDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServeDeploymentStatus)(nil), (*ServeDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServeDeploymentStatus_To_v1beta1_ServeDeploymentStatus(a.(*v1alpha1.ServeDeploymentStatus), b.(*ServeDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerGroupSpec)(nil), (*v1alpha1.WorkerGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_WorkerGroupSpec_To_v1alpha1_WorkerGroupSpec(a.(*WorkerGroupSpec), b.(*v1alpha1.WorkerGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.WorkerGroupSpec)(nil), (*WorkerGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerGroupSpec_To_v1beta1_WorkerGroupSpec(a.(*v1alpha1.WorkerGroupSpec), b.(*WorkerGroupSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_AppStatus_To_v1alpha1_AppStatus(in *AppStatus, out *v1alpha1.AppStatus, s conversion.Scope) error {
	out.Status = in.Status
	out.Message = in.Message
	out.LastUpdateTime = (*v1.Time)(unsafe.Pointer(in.LastUpdateTime))
	out.HealthLastUpdateTime = (*v1.Time)(unsafe.Pointer(in.HealthLastUpdateTime))
	return nil
}

// Convert_v1beta1_AppStatus_To_v1alpha1_AppStatus is an autogenerated conversion function.
func Convert_v1beta1_AppStatus_To_v1alpha1_AppStatus(in *AppStatus, out *v1alpha1.AppStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_AppStatus_To_v1alpha1_AppStatus(in, out, s)
}

func autoConvert_v1alpha1_AppStatus_To_v1beta1_AppStatus(in *v1alpha1.AppStatus, out *AppStatus, s conversion.Scope) error {
	out.Status = in.Status
	out.Message = in.Message
	out.LastUpdateTime = (*v1.Time)(unsafe.Pointer(in.LastUpdateTime))
	out.HealthLastUpdateTime = (*v1.Time)(unsafe.Pointer(in.HealthLastUpdateTime))
	return nil
}

// Convert_v1alpha1_AppStatus_To_v1beta1_AppStatus is an autogenerated conversion function.
func Convert_v1alpha1_AppStatus_To_v1beta1_AppStatus(in *v1alpha1.AppStatus, out *AppStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppStatus_To_v1beta1_AppStatus(in, out, s)
}

func autoConvert_v1beta1_AutoscalerOptions_To_v1alpha1_AutoscalerOptions(in *AutoscalerOptions, out *v1alpha1.AutoscalerOptions, s conversion.Scope) error {
	out.Resources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Image = (*string)(unsafe.Pointer(in.Image))
	out.ImagePullPolicy = (*corev1.PullPolicy)(unsafe.Pointer(in.ImagePullPolicy))
	out.Env = *(*[]corev1.EnvVar)(unsafe.Pointer(&in.Env))
	out.EnvFrom = *(*[]corev1.EnvFromSource)(unsafe.Pointer(&in.EnvFrom))
	out.VolumeMounts = *(*[]corev1.VolumeMount)(unsafe.Pointer(&in.VolumeMounts))
	out.SecurityContext = (*corev1.SecurityContext)(unsafe.Pointer(in.SecurityContext))
	out.IdleTimeoutSeconds = (*int32)(unsafe.Pointer(in.IdleTimeoutSeconds))
	out.UpscalingMode = (*v1alpha1.UpscalingMode)(unsafe.Pointer(in.UpscalingMode))
	return nil
}

// Convert_v1beta1_AutoscalerOptions_To_v1alpha1_AutoscalerOptions is an autogenerated conversion function.
func Convert_v1beta1_AutoscalerOptions_To_v1alpha1_AutoscalerOptions(in *AutoscalerOptions, out *v1alpha1.AutoscalerOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_AutoscalerOptions_To_v1alpha1_AutoscalerOptions(in, out, s)
}

func autoConvert_v1alpha1_AutoscalerOptions_To_v1beta1_AutoscalerOptions(in *v1alpha1.AutoscalerOptions, out *AutoscalerOptions, s conversion.Scope) error {
	out.Resources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Image = (*string)(unsafe.Pointer(in.Image))
	out.ImagePullPolicy = (*corev1.PullPolicy)(unsafe.Pointer(in.ImagePullPolicy))
	out.Env = *(*[]corev1.EnvVar)(unsafe.Pointer(&in.Env))
	out.EnvFrom = *(*[]corev1.EnvFromSource)(unsafe.Pointer(&in.EnvFrom))
	out.VolumeMounts = *(*[]corev1.VolumeMount)(unsafe.Pointer(&in.VolumeMounts))
	out.SecurityContext = (*corev1.SecurityContext)(unsafe.Pointer(in.SecurityContext))
	out.IdleTimeoutSeconds = (*int32)(unsafe.Pointer(in.IdleTimeoutSeconds))
	out.UpscalingMode = (*UpscalingMode)(unsafe.Pointer(in.UpscalingMode))
	return nil
}

// Convert_v1alpha1_AutoscalerOptions_To_v1beta1_AutoscalerOptions is an autogenerated conversion function.
func Convert_v1alpha1_AutoscalerOptions_To_v1beta1_AutoscalerOptions(in *v1alpha1.AutoscalerOptions, out *AutoscalerOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_AutoscalerOptions_To_v1beta1_AutoscalerOptions(in, out, s)
}

func autoConvert_v1beta1_DashboardStatus_To_v1alpha1_DashboardStatus(in *DashboardStatus, out *v1alpha1.DashboardStatus, s conversion.Scope) error {
	out.IsHealthy = in.IsHealthy
	out.LastUpdateTime = (*v1.Time)(unsafe.Pointer(in.LastUpdateTime))
	out.HealthLastUpdateTime = (*v1.Time)(unsafe.Pointer(in.HealthLastUpdateTime))
	return nil
}

// Convert_v1beta1_DashboardStatus_To_v1alpha1_DashboardStatus is an autogenerated conversion function.
func Convert_v1beta1_DashboardStatus_To_v1alpha1_DashboardStatus(in *DashboardStatus, out *v1alpha1.DashboardStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_DashboardStatus_To_v1alpha1_DashboardStatus(in, out, s)
}

func autoConvert_v1alpha1_DashboardStatus_To_v1beta1_DashboardStatus(in *v1alpha1.DashboardStatus, out *DashboardStatus, s conversion.Scope) error {
	out.IsHealthy = in.IsHealthy
	out.LastUpdateTime = (*v1.Time)(unsafe.Pointer(in.LastUpdateTime))
	out.HealthLastUpdateTime = (*v1.Time)(unsafe.Pointer(in.HealthLastUpdateTime))
	return nil
}

// Convert_v1alpha1_DashboardStatus_To_v1beta1_DashboardStatus is an autogenerated conversion function.
func Convert_v1alpha1_DashboardStatus_To_v1beta1_DashboardStatus(in *v1alpha1.DashboardStatus, out *DashboardStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DashboardStatus_To_v1beta1_DashboardStatus(in, out, s)
}

func autoConvert_v1beta1_HeadGroupSpec_To_v1alpha1_HeadGroupSpec(in *HeadGroupSpec, out *v1alpha1.HeadGroupSpec, s conversion.Scope) error {
	out.ServiceType = corev1.ServiceType(in.ServiceType)
	out.HeadService = (*corev1.Service)(unsafe.Pointer(in.HeadService))
	out.EnableIngress = (*bool)(unsafe.Pointer(in.EnableIngress))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.RayStartParams = *(*map[string]string)(unsafe.Pointer(&in.RayStartParams))
	out.Template = in.Template
	return nil
}

// Convert_v1beta1_HeadGroupSpec_To_v1alpha1_HeadGroupSpec is an autogenerated conversion function.
func Convert_v1beta1_HeadGroupSpec_To_v1alpha1_HeadGroupSpec(in *HeadGroupSpec, out *v1alpha1.HeadGroupSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_HeadGroupSpec_To_v1alpha1_HeadGroupSpec(in, out, s)
}

func autoConvert_v1alpha1_HeadGroupSpec_To_v1beta1_HeadGroupSpec(in *v1alpha1.HeadGroupSpec, out *HeadGroupSpec, s conversion.Scope) error {
	out.ServiceType = corev1.ServiceType(in.ServiceType)
	out.HeadService = (*corev1.Service)(unsafe.Pointer(in.HeadService))
	out.EnableIngress = (*bool)(unsafe.Pointer(in.EnableIngress))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.RayStartParams = *(*map[string]string)(unsafe.Pointer(&in.RayStartParams))
	out.Template = in.Template
	return nil
}

// Convert_v1alpha1_HeadGroupSpec_To_v1beta1_HeadGroupSpec is an autogenerated conversion function.
func Convert_v1alpha1_HeadGroupSpec_To_v1beta1_HeadGroupSpec(in *v1alpha1.HeadGroupSpec, out *HeadGroupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_HeadGroupSpec_To_v1beta1_HeadGroupSpec(in, out, s)
}

func autoConvert_v1beta1_HeadInfo_To_v1alpha1_HeadInfo(in *HeadInfo, out *v1alpha1.HeadInfo, s conversion.Scope) error {
	out.PodIP = in.PodIP
	out.ServiceIP = in.ServiceIP
	return nil
}

// Convert_v1beta1_HeadInfo_To_v1alpha1_HeadInfo is an autogenerated conversion function.
func Convert_v1beta1_HeadInfo_To_v1alpha1_HeadInfo(in *HeadInfo, out *v1alpha1.HeadInfo, s conversion.Scope) error {
	return autoConvert_v1beta1_HeadInfo_To_v1alpha1_HeadInfo(in, out, s)
}

func autoConvert_v1alpha1_HeadInfo_To_v1beta1_HeadInfo(in *v1alpha1.HeadInfo, out *HeadInfo, s conversion.Scope) error {
	out.PodIP = in.PodIP
	out.ServiceIP = in.ServiceIP
	return nil
}

// Convert_v1alpha1_HeadInfo_To_v1beta1_HeadInfo is an autogenerated conversion function.
func Convert_v1alpha1_HeadInfo_To_v1beta1_HeadInfo(in *v1alpha1.HeadInfo, out *HeadInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_HeadInfo_To_v1beta1_HeadInfo(in, out, s)
}

func autoConvert_v1beta1_RayActorOptionSpec_To_v1alpha1_RayActorOptionSpec(in *RayActorOptionSpec, out *v1alpha1.RayActorOptionSpec, s conversion.Scope) error {
	out.RuntimeEnv = in.RuntimeEnv
	out.NumCpus = (*float64)(unsafe.Pointer(in.NumCpus))
	out.NumGpus = (*float64)(unsafe.Pointer(in.NumGpus))
	out.Memory = (*int32)(unsafe.Pointer(in.Memory))
	out.ObjectStoreMemory = (*int32)(unsafe.Pointer(in.ObjectStoreMemory))
	out.Resources = in.Resources
	out.AcceleratorType = in.AcceleratorType
	return nil
}

// Convert_v1beta1_RayActorOptionSpec_To_v1alpha1_RayActorOptionSpec is an autogenerated conversion function.
func Convert_v1beta1_RayActorOptionSpec_To_v1alpha1_RayActorOptionSpec(in *RayActorOptionSpec, out *v1alpha1.RayActorOptionSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RayActorOptionSpec_To_v1alpha1_RayActorOptionSpec(in, out, s)
}

func autoConvert_v1alpha1_RayActorOptionSpec_To_v1beta1_RayActorOptionSpec(in *v1alpha1.RayActorOptionSpec, out *RayActorOptionSpec, s conversion.Scope) error {
	out.RuntimeEnv = in.RuntimeEnv
	out.NumCpus = (*float64)(unsafe.Pointer(in.NumCpus))
	out.NumGpus = (*float64)(unsafe.Pointer(in.NumGpus))
	out.Memory = (*int32)(unsafe.Pointer(in.Memory))
	out.ObjectStoreMemory = (*int32)(unsafe.Pointer(in.ObjectStoreMemory))
	out.Resources = in.Resources
	out.AcceleratorType = in.AcceleratorType
	return nil
}

// Convert_v1alpha1_RayActorOptionSpec_To_v1beta1_RayActorOptionSpec is an autogenerated conversion function.
func Convert_v1alpha1_RayActorOptionSpec_To_v1beta1_RayActorOptionSpec(in *v1alpha1.RayActorOptionSpec, out *RayActorOptionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayActorOptionSpec_To_v1beta1_RayActorOptionSpec(in, out, s)
}

func autoConvert_v1beta1_RayCluster_To_v1alpha1_RayCluster(in *RayCluster, out *v1alpha1.RayCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RayClusterSpec_To_v1alpha1_RayClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RayClusterStatus_To_v1alpha1_RayClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RayCluster_To_v1alpha1_RayCluster is an autogenerated conversion function.
func Convert_v1beta1_RayCluster_To_v1alpha1_RayCluster(in *RayCluster, out *v1alpha1.RayCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_RayCluster_To_v1alpha1_RayCluster(in, out, s)
}

func autoConvert_v1alpha1_RayCluster_To_v1beta1_RayCluster(in *v1alpha1.RayCluster, out *RayCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RayClusterSpec_To_v1beta1_RayClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RayClusterStatus_To_v1beta1_RayClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RayCluster_To_v1beta1_RayCluster is an autogenerated conversion function.
func Convert_v1alpha1_RayCluster_To_v1beta1_RayCluster(in *v1alpha1.RayCluster, out *RayCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayCluster_To_v1beta1_RayCluster(in, out, s)
}

func autoConvert_v1beta1_RayClusterList_To_v1alpha1_RayClusterList(in *RayClusterList, out *v1alpha1.RayClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.RayCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_RayClusterList_To_v1alpha1_RayClusterList is an autogenerated conversion function.
func Convert_v1beta1_RayClusterList_To_v1alpha1_RayClusterList(in *RayClusterList, out *v1alpha1.RayClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_RayClusterList_To_v1alpha1_RayClusterList(in, out, s)
}

func autoConvert_v1alpha1_RayClusterList_To_v1beta1_RayClusterList(in *v1alpha1.RayClusterList, out *RayClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RayCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RayClusterList_To_v1beta1_RayClusterList is an autogenerated conversion function.
func Convert_v1alpha1_RayClusterList_To_v1beta1_RayClusterList(in *v1alpha1.RayClusterList, out *RayClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayClusterList_To_v1beta1_RayClusterList(in, out, s)
}

func autoConvert_v1beta1_RayClusterSpec_To_v1alpha1_RayClusterSpec(in *RayClusterSpec, out *v1alpha1.RayClusterSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_HeadGroupSpec_To_v1alpha1_HeadGroupSpec(&in.HeadGroupSpec, &out.HeadGroupSpec, s); err != nil {
		return err
	}
	out.WorkerGroupSpecs = *(*[]v1alpha1.WorkerGroupSpec)(unsafe.Pointer(&in.WorkerGroupSpecs))
	out.RayVersion = in.RayVersion
	out.EnableInTreeAutoscaling = (*bool)(unsafe.Pointer(in.EnableInTreeAutoscaling))
	out.AutoscalerOptions = (*v1alpha1.AutoscalerOptions)(unsafe.Pointer(in.AutoscalerOptions))
	out.HeadServiceAnnotations = *(*map[string]string)(unsafe.Pointer(&in.HeadServiceAnnotations))
	return nil
}

// Convert_v1beta1_RayClusterSpec_To_v1alpha1_RayClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_RayClusterSpec_To_v1alpha1_RayClusterSpec(in *RayClusterSpec, out *v1alpha1.RayClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RayClusterSpec_To_v1alpha1_RayClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_RayClusterSpec_To_v1beta1_RayClusterSpec(in *v1alpha1.RayClusterSpec, out *RayClusterSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_HeadGroupSpec_To_v1beta1_HeadGroupSpec(&in.HeadGroupSpec, &out.HeadGroupSpec, s); err != nil {
		return err
	}
	out.WorkerGroupSpecs = *(*[]WorkerGroupSpec)(unsafe.Pointer(&in.WorkerGroupSpecs))
	out.RayVersion = in.RayVersion
	out.EnableInTreeAutoscaling = (*bool)(unsafe.Pointer(in.EnableInTreeAutoscaling))
	out.AutoscalerOptions = (*AutoscalerOptions)(unsafe.Pointer(in.AutoscalerOptions))
	out.HeadServiceAnnotations = *(*map[string]string)(unsafe.Pointer(&in.HeadServiceAnnotations))
	return nil
}

// Convert_v1alpha1_RayClusterSpec_To_v1beta1_RayClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_RayClusterSpec_To_v1beta1_RayClusterSpec(in *v1alpha1.RayClusterSpec, out *RayClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayClusterSpec_To_v1beta1_RayClusterSpec(in, out, s)
}

func autoConvert_v1beta1_RayClusterStatus_To_v1alpha1_RayClusterStatus(in *RayClusterStatus, out *v1alpha1.RayClusterStatus, s conversion.Scope) error {
	out.State = v1alpha1.ClusterState(in.State)
	out.AvailableWorkerReplicas = in.AvailableWorkerReplicas
	out.DesiredWorkerReplicas = in.DesiredWorkerReplicas
	out.MinWorkerReplicas = in.MinWorkerReplicas
	out.MaxWorkerReplicas = in.MaxWorkerReplicas
	out.LastUpdateTime = (*v1.Time)(unsafe.Pointer(in.LastUpdateTime))
	out.Endpoints = *(*map[string]string)(unsafe.Pointer(&in.Endpoints))
	if err := Convert_v1beta1_HeadInfo_To_v1alpha1_HeadInfo(&in.Head, &out.Head, s); err != nil {
		return err
	}
	out.Reason = in.Reason
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_v1beta1_RayClusterStatus_To_v1alpha1_RayClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_RayClusterStatus_To_v1alpha1_RayClusterStatus(in *RayClusterStatus, out *v1alpha1.RayClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RayClusterStatus_To_v1alpha1_RayClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_RayClusterStatus_To_v1beta1_RayClusterStatus(in *v1alpha1.RayClusterStatus, out *RayClusterStatus, s conversion.Scope) error {
	out.State = ClusterState(in.State)
	out.AvailableWorkerReplicas = in.AvailableWorkerReplicas
	out.DesiredWorkerReplicas = in.DesiredWorkerReplicas
	out.MinWorkerReplicas = in.MinWorkerReplicas
	out.MaxWorkerReplicas = in.MaxWorkerReplicas
	out.LastUpdateTime = (*v1.Time)(unsafe.Pointer(in.LastUpdateTime))
	out.Endpoints = *(*map[string]string)(unsafe.Pointer(&in.Endpoints))
	if err := Convert_v1alpha1_HeadInfo_To_v1beta1_HeadInfo(&in.Head, &out.Head, s); err != nil {
		return err
	}
	out.Reason = in.Reason
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_v1alpha1_RayClusterStatus_To_v1beta1_RayClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_RayClusterStatus_To_v1beta1_RayClusterStatus(in *v1alpha1.RayClusterStatus, out *RayClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayClusterStatus_To_v1beta1_RayClusterStatus(in, out, s)
}

func autoConvert_v1beta1_RayService_To_v1alpha1_RayService(in *RayService, out *v1alpha1.RayService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RayServiceSpec_To_v1alpha1_RayServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RayServiceStatuses_To_v1alpha1_RayServiceStatuses(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RayService_To_v1alpha1_RayService is an autogenerated conversion function.
func Convert_v1beta1_RayService_To_v1alpha1_RayService(in *RayService, out *v1alpha1.RayService, s conversion.Scope) error {
	return autoConvert_v1beta1_RayService_To_v1alpha1_RayService(in, out, s)
}

func autoConvert_v1alpha1_RayService_To_v1beta1_RayService(in *v1alpha1.RayService, out *RayService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RayServiceSpec_To_v1beta1_RayServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RayServiceStatuses_To_v1beta1_RayServiceStatuses(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RayService_To_v1beta1_RayService is an autogenerated conversion function.
func Convert_v1alpha1_RayService_To_v1beta1_RayService(in *v1alpha1.RayService, out *RayService, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayService_To_v1beta1_RayService(in, out, s)
}

func autoConvert_v1beta1_RayServiceList_To_v1alpha1_RayServiceList(in *RayServiceList, out *v1alpha1.RayServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.RayService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_RayServiceList_To_v1alpha1_RayServiceList is an autogenerated conversion function.
func Convert_v1beta1_RayServiceList_To_v1alpha1_RayServiceList(in *RayServiceList, out *v1alpha1.RayServiceList, s conversion.Scope) error {
	return autoConvert_v1beta1_RayServiceList_To_v1alpha1_RayServiceList(in, out, s)
}

func autoConvert_v1alpha1_RayServiceList_To_v1beta1_RayServiceList(in *v1alpha1.RayServiceList, out *RayServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RayService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RayServiceList_To_v1beta1_RayServiceList is an autogenerated conversion function.
func Convert_v1alpha1_RayServiceList_To_v1beta1_RayServiceList(in *v1alpha1.RayServiceList, out *RayServiceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayServiceList_To_v1beta1_RayServiceList(in, out, s)
}

func autoConvert_v1beta1_RayServiceSpec_To_v1alpha1_RayServiceSpec(in *RayServiceSpec, out *v1alpha1.RayServiceSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_ServeDeploymentGraphSpec_To_v1alpha1_ServeDeploymentGraphSpec(&in.ServeDeploymentGraphSpec, &out.ServeDeploymentGraphSpec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RayClusterSpec_To_v1alpha1_RayClusterSpec(&in.RayClusterSpec, &out.RayClusterSpec, s); err != nil {
		return err
	}
	out.ServiceUnhealthySecondThreshold = (*int32)(unsafe.Pointer(in.ServiceUnhealthySecondThreshold))
	out.DeploymentUnhealthySecondThreshold = (*int32)(unsafe.Pointer(in.DeploymentUnhealthySecondThreshold))
	return nil
}

// Convert_v1beta1_RayServiceSpec_To_v1alpha1_RayServiceSpec is an autogenerated conversion function.
func Convert_v1beta1_RayServiceSpec_To_v1alpha1_RayServiceSpec(in *RayServiceSpec, out *v1alpha1.RayServiceSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RayServiceSpec_To_v1alpha1_RayServiceSpec(in, out, s)
}

func autoConvert_v1alpha1_RayServiceSpec_To_v1beta1_RayServiceSpec(in *v1alpha1.RayServiceSpec, out *RayServiceSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ServeDeploymentGraphSpec_To_v1beta1_ServeDeploymentGraphSpec(&in.ServeDeploymentGraphSpec, &out.ServeDeploymentGraphSpec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RayClusterSpec_To_v1beta1_RayClusterSpec(&in.RayClusterSpec, &out.RayClusterSpec, s); err != nil {
		return err
	}
	out.ServiceUnhealthySecondThreshold = (*int32)(unsafe.Pointer(in.ServiceUnhealthySecondThreshold))
	out.DeploymentUnhealthySecondThreshold = (*int32)(unsafe.Pointer(in.DeploymentUnhealthySecondThreshold))
	return nil
}

// Convert_v1alpha1_RayServiceSpec_To_v1beta1_RayServiceSpec is an autogenerated conversion function.
func Convert_v1alpha1_RayServiceSpec_To_v1beta1_RayServiceSpec(in *v1alpha1.RayServiceSpec, out *RayServiceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayServiceSpec_To_v1beta1_RayServiceSpec(in, out, s)
}

func autoConvert_v1beta1_RayServiceStatus_To_v1alpha1_RayServiceStatus(in *RayServiceStatus, out *v1alpha1.RayServiceStatus, s conversion.Scope) error {
	if err := Convert_v1beta1_AppStatus_To_v1alpha1_AppStatus(&in.ApplicationStatus, &out.ApplicationStatus, s); err != nil {
		return err
	}
	out.ServeStatuses = *(*[]v1alpha1.ServeDeploymentStatus)(unsafe.Pointer(&in.ServeStatuses))
	if err := Convert_v1beta1_DashboardStatus_To_v1alpha1_DashboardStatus(&in.DashboardStatus, &out.DashboardStatus, s); err != nil {
		return err
	}
	out.RayClusterName = in.RayClusterName
	if err := Convert_v1beta1_RayClusterStatus_To_v1alpha1_RayClusterStatus(&in.RayClusterStatus, &out.RayClusterStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RayServiceStatus_To_v1alpha1_RayServiceStatus is an autogenerated conversion function.
func Convert_v1beta1_RayServiceStatus_To_v1alpha1_RayServiceStatus(in *RayServiceStatus, out *v1alpha1.RayServiceStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RayServiceStatus_To_v1alpha1_RayServiceStatus(in, out, s)
}

func autoConvert_v1alpha1_RayServiceStatus_To_v1beta1_RayServiceStatus(in *v1alpha1.RayServiceStatus, out *RayServiceStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_AppStatus_To_v1beta1_AppStatus(&in.ApplicationStatus, &out.ApplicationStatus, s); err != nil {
		return err
	}
	out.ServeStatuses = *(*[]ServeDeploymentStatus)(unsafe.Pointer(&in.ServeStatuses))
	if err := Convert_v1alpha1_DashboardStatus_To_v1beta1_DashboardStatus(&in.DashboardStatus, &out.DashboardStatus, s); err != nil {
		return err
	}
	out.RayClusterName = in.RayClusterName
	if err := Convert_v1alpha1_RayClusterStatus_To_v1beta1_RayClusterStatus(&in.RayClusterStatus, &out.RayClusterStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RayServiceStatus_To_v1beta1_RayServiceStatus is an autogenerated conversion function.
func Convert_v1alpha1_RayServiceStatus_To_v1beta1_RayServiceStatus(in *v1alpha1.RayServiceStatus, out *RayServiceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayServiceStatus_To_v1beta1_RayServiceStatus(in, out, s)
}

func autoConvert_v1beta1_RayServiceStatuses_To_v1alpha1_RayServiceStatuses(in *RayServiceStatuses, out *v1alpha1.RayServiceStatuses, s conversion.Scope) error {
	if err := Convert_v1beta1_RayServiceStatus_To_v1alpha1_RayServiceStatus(&in.ActiveServiceStatus, &out.ActiveServiceStatus, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RayServiceStatus_To_v1alpha1_RayServiceStatus(&in.PendingServiceStatus, &out.PendingServiceStatus, s); err != nil {
		return err
	}
	out.ServiceStatus = v1alpha1.ServiceStatus(in.ServiceStatus)
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_v1beta1_RayServiceStatuses_To_v1alpha1_RayServiceStatuses is an autogenerated conversion function.
func Convert_v1beta1_RayServiceStatuses_To_v1alpha1_RayServiceStatuses(in *RayServiceStatuses, out *v1alpha1.RayServiceStatuses, s conversion.Scope) error {
	return autoConvert_v1beta1_RayServiceStatuses_To_v1alpha1_RayServiceStatuses(in, out, s)
}

func autoConvert_v1alpha1_RayServiceStatuses_To_v1beta1_RayServiceStatuses(in *v1alpha1.RayServiceStatuses, out *RayServiceStatuses, s conversion.Scope) error {
	if err := Convert_v1alpha1_RayServiceStatus_To_v1beta1_RayServiceStatus(&in.ActiveServiceStatus, &out.ActiveServiceStatus, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RayServiceStatus_To_v1beta1_RayServiceStatus(&in.PendingServiceStatus, &out.PendingServiceStatus, s); err != nil {
		return err
	}
	out.ServiceStatus = ServiceStatus(in.ServiceStatus)
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_v1alpha1_RayServiceStatuses_To_v1beta1_RayServiceStatuses is an autogenerated conversion function.
func Convert_v1alpha1_RayServiceStatuses_To_v1beta1_RayServiceStatuses(in *v1alpha1.RayServiceStatuses, out *RayServiceStatuses, s conversion.Scope) error {
	return autoConvert_v1alpha1_RayServiceStatuses_To_v1beta1_RayServiceStatuses(in, out, s)
}

func autoConvert_v1beta1_ScaleStrategy_To_v1alpha1_ScaleStrategy(in *ScaleStrategy, out *v1alpha1.ScaleStrategy, s conversion.Scope) error {
	out.WorkersToDelete = *(*[]string)(unsafe.Pointer(&in.WorkersToDelete))
	return nil
}

// Convert_v1beta1_ScaleStrategy_To_v1alpha1_ScaleStrategy is an autogenerated conversion function.
func Convert_v1beta1_ScaleStrategy_To_v1alpha1_ScaleStrategy(in *ScaleStrategy, out *v1alpha1.ScaleStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_ScaleStrategy_To_v1alpha1_ScaleStrategy(in, out, s)
}

func autoConvert_v1alpha1_ScaleStrategy_To_v1beta1_ScaleStrategy(in *v1alpha1.ScaleStrategy, out *ScaleStrategy, s conversion.Scope) error {
	out.WorkersToDelete = *(*[]string)(unsafe.Pointer(&in.WorkersToDelete))
	return nil
}

// Convert_v1alpha1_ScaleStrategy_To_v1beta1_ScaleStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ScaleStrategy_To_v1beta1_ScaleStrategy(in *v1alpha1.ScaleStrategy, out *ScaleStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScaleStrategy_To_v1beta1_ScaleStrategy(in, out, s)
}

func autoConvert_v1beta1_ServeConfigSpec_To_v1alpha1_ServeConfigSpec(in *ServeConfigSpec, out *v1alpha1.ServeConfigSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.NumReplicas = (*int32)(unsafe.Pointer(in.NumReplicas))
	out.RoutePrefix = in.RoutePrefix
	out.MaxConcurrentQueries = (*int32)(unsafe.Pointer(in.MaxConcurrentQueries))
	out.UserConfig = in.UserConfig
	out.AutoscalingConfig = in.AutoscalingConfig
	out.GracefulShutdownWaitLoopS = (*int32)(unsafe.Pointer(in.GracefulShutdownWaitLoopS))
	out.GracefulShutdownTimeoutS = (*int32)(unsafe.Pointer(in.GracefulShutdownTimeoutS))
	out.HealthCheckPeriodS = (*int32)(unsafe.Pointer(in.HealthCheckPeriodS))
	out.HealthCheckTimeoutS = (*int32)(unsafe.Pointer(in.HealthCheckTimeoutS))
	if err := Convert_v1beta1_RayActorOptionSpec_To_v1alpha1_RayActorOptionSpec(&in.RayActorOptions, &out.RayActorOptions, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ServeConfigSpec_To_v1alpha1_ServeConfigSpec is an autogenerated conversion function.
func Convert_v1beta1_ServeConfigSpec_To_v1alpha1_ServeConfigSpec(in *ServeConfigSpec, out *v1alpha1.ServeConfigSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ServeConfigSpec_To_v1alpha1_ServeConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_ServeConfigSpec_To_v1beta1_ServeConfigSpec(in *v1alpha1.ServeConfigSpec, out *ServeConfigSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.NumReplicas = (*int32)(unsafe.Pointer(in.NumReplicas))
	out.RoutePrefix = in.RoutePrefix
	out.MaxConcurrentQueries = (*int32)(unsafe.Pointer(in.MaxConcurrentQueries))
	out.UserConfig = in.UserConfig
	out.AutoscalingConfig = in.AutoscalingConfig
	out.GracefulShutdownWaitLoopS = (*int32)(unsafe.Pointer(in.GracefulShutdownWaitLoopS))
	out.GracefulShutdownTimeoutS = (*int32)(unsafe.Pointer(in.GracefulShutdownTimeoutS))
	out.HealthCheckPeriodS = (*int32)(unsafe.Pointer(in.HealthCheckPeriodS))
	out.HealthCheckTimeoutS = (*int32)(unsafe.Pointer(in.HealthCheckTimeoutS))
	if err := Convert_v1alpha1_RayActorOptionSpec_To_v1beta1_RayActorOptionSpec(&in.RayActorOptions, &out.RayActorOptions, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServeConfigSpec_To_v1beta1_ServeConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_ServeConfigSpec_To_v1beta1_ServeConfigSpec(in *v1alpha1.ServeConfigSpec, out *ServeConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServeConfigSpec_To_v1beta1_ServeConfigSpec(in, out, s)
}

func autoConvert_v1beta1_ServeDeploymentGraphSpec_To_v1alpha1_ServeDeploymentGraphSpec(in *ServeDeploymentGraphSpec, out *v1alpha1.ServeDeploymentGraphSpec, s conversion.Scope) error {
	out.ImportPath = in.ImportPath
	out.RuntimeEnv = in.RuntimeEnv
	out.ServeConfigSpecs = *(*[]v1alpha1.ServeConfigSpec)(unsafe.Pointer(&in.ServeConfigSpecs))
	out.Port = in.Port
	return nil
}

// Convert_v1beta1_ServeDeploymentGraphSpec_To_v1alpha1_ServeDeploymentGraphSpec is an autogenerated conversion function.
func Convert_v1beta1_ServeDeploymentGraphSpec_To_v1alpha1_ServeDeploymentGraphSpec(in *ServeDeploymentGraphSpec, out *v1alpha1.ServeDeploymentGraphSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ServeDeploymentGraphSpec_To_v1alpha1_ServeDeploymentGraphSpec(in, out, s)
}

func autoConvert_v1alpha1_ServeDeploymentGraphSpec_To_v1beta1_ServeDeploymentGraphSpec(in *v1alpha1.ServeDeploymentGraphSpec, out *ServeDeploymentGraphSpec, s conversion.Scope) error {
	out.ImportPath = in.ImportPath
	out.RuntimeEnv = in.RuntimeEnv
	out.ServeConfigSpecs = *(*[]ServeConfigSpec)(unsafe.Pointer(&in.ServeConfigSpecs))
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_ServeDeploymentGraphSpec_To_v1beta1_ServeDeploymentGraphSpec is an autogenerated conversion function.
func Convert_v1alpha1_ServeDeploymentGraphSpec_To_v1beta1_ServeDeploymentGraphSpec(in *v1alpha1.ServeDeploymentGraphSpec, out *ServeDeploymentGraphSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServeDeploymentGraphSpec_To_v1beta1_ServeDeploymentGraphSpec(in, out, s)
}

func autoConvert_v1beta1_ServeDeploymentStatus_To_v1alpha1_ServeDeploymentStatus(in *ServeDeploymentStatus, out *v1alpha1.ServeDeploymentStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = in.Status
	out.Message = in.Message
	out.LastUpdateTime = (*v1.Time)(unsafe.Pointer(in.LastUpdateTime))
	out.HealthLastUpdateTime = (*v1.Time)(unsafe.Pointer(in.HealthLastUpdateTime))
	return nil
}

// Convert_v1beta1_ServeDeploymentStatus_To_v1alpha1_ServeDeploymentStatus is an autogenerated conversion function.
func Convert_v1beta1_ServeDeploymentStatus_To_v1alpha1_ServeDeploymentStatus(in *ServeDeploymentStatus, out *v1alpha1.ServeDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ServeDeploymentStatus_To_v1alpha1_ServeDeploymentStatus(in, out, s)
}

func autoConvert_v1alpha1_ServeDeploymentStatus_To_v1beta1_ServeDeploymentStatus(in *v1alpha1.ServeDeploymentStatus, out *ServeDeploymentStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = in.Status
	out.Message = in.Message
	out.LastUpdateTime = (*v1.Time)(unsafe.Pointer(in.LastUpdateTime))
	out.HealthLastUpdateTime = (*v1.Time)(unsafe.Pointer(in.HealthLastUpdateTime))
	return nil
}

// Convert_v1alpha1_ServeDeploymentStatus_To_v1beta1_ServeDeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha1_ServeDeploymentStatus_To_v1beta1_ServeDeploymentStatus(in *v1alpha1.ServeDeploymentStatus, out *ServeDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServeDeploymentStatus_To_v1beta1_ServeDeploymentStatus(in, out, s)
}

func autoConvert_v1beta1_WorkerGroupSpec_To_v1alpha1_WorkerGroupSpec(in *WorkerGroupSpec, out *v1alpha1.WorkerGroupSpec, s conversion.Scope) error {
	out.GroupName = in.GroupName
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MinReplicas = (*int32)(unsafe.Pointer(in.MinReplicas))
	out.MaxReplicas = (*int32)(unsafe.Pointer(in.MaxReplicas))
	out.RayStartParams = *(*map[string]string)(unsafe.Pointer(&in.RayStartParams))
	out.Template = in.Template
	if err := Convert_v1beta1_ScaleStrategy_To_v1alpha1_ScaleStrategy(&in.ScaleStrategy, &out.ScaleStrategy, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_WorkerGroupSpec_To_v1alpha1_WorkerGroupSpec is an autogenerated conversion function.
func Convert_v1beta1_WorkerGroupSpec_To_v1alpha1_WorkerGroupSpec(in *WorkerGroupSpec, out *v1alpha1.WorkerGroupSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_WorkerGroupSpec_To_v1alpha1_WorkerGroupSpec(in, out, s)
}

func autoConvert_v1alpha1_WorkerGroupSpec_To_v1beta1_WorkerGroupSpec(in *v1alpha1.WorkerGroupSpec, out *WorkerGroupSpec, s conversion.Scope) error {
	out.GroupName = in.GroupName
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MinReplicas = (*int32)(unsafe.Pointer(in.MinReplicas))
	out.MaxReplicas = (*int32)(unsafe.Pointer(in.MaxReplicas))
	out.RayStartParams = *(*map[string]string)(unsafe.Pointer(&in.RayStartParams))
	out.Template = in.Template
	if err := Convert_v1alpha1_ScaleStrategy_To_v1beta1_ScaleStrategy(&in.ScaleStrategy, &out.ScaleStrategy, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_WorkerGroupSpec_To_v1beta1_WorkerGroupSpec is an autogenerated conversion function.
func Convert_v1alpha1_WorkerGroupSpec_To_v1beta1_WorkerGroupSpec(in *v1alpha1.WorkerGroupSpec, out *WorkerGroupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerGroupSpec_To_v1beta1_WorkerGroupSpec(in, out, s)
}
