# permissions for end users to view rayclusters.
{{- if and .Values.rbacEnable (not .Values.singleNamespaceInstall) }}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{ include "kuberay-operator.labels" . | nindent 4 }}
  name: raycluster-viewer-role
rules:
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayclusters/status
  verbs:
  - get
{{- end }}
