{{- if and .Values.rbacEnable (not .Values.singleNamespaceInstall) }}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "kuberay-operator.labels" . | indent 4 }}
  name: {{ include "kuberay-operator.fullname" . }}
{{ include "role.consistentRules" (dict "batchSchedulerEnabled" .Values.batchScheduler.enabled "batchSchedulerName" .Values.batchScheduler.name) }}
{{- end }}
