# permissions for end users to edit rayjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raycronjob-editor-role
rules:
- apiGroups:
  - ray.io
  resources:
  - raycronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ray.io
  resources:
  - raycronjobs/status
  verbs:
  - get
