---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rayjob-editor-role
rules:
- apiGroups:
  - ray.io
  resources:
  - rayjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
