// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// RayClusterListerExpansion allows custom methods to be added to
// RayClusterLister.
type RayClusterListerExpansion interface{}

// RayClusterNamespaceListerExpansion allows custom methods to be added to
// RayClusterNamespaceLister.
type RayClusterNamespaceListerExpansion interface{}
