# Strategic merge patch for kuberay-operator Deployment (test / CI only).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
spec:
  template:
    spec:
      containers:
      - name: kuberay-operator
        args:
        - --feature-gates=RayClusterStatusConditions=true,RayJobDeletionPolicy=true,RayMultiHostIndexing=true
