name: "Close inactive issues"

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          stale-pr-message: "This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          days-before-stale: 60
          days-before-close: 30
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale."
          close-pr-message: "This pull request was closed because it has been inactive for 30 days since being marked as stale."
